### ISSUE TITLE
Forum for members and ErlEF followers

### ISSUE THREAD

**Issue by benoitc** [erlef/infra-wg#61]
ticket to track the setup of the erlef forum. As the project will grow, more tickets will be linked to it.

### Goal

Setup a place for asynchronous discussions allowing members and ErlEF follower to interract at any tme across the timezone. It will complement the the synchronous media like the Slack and IRC channels.

### Milestones

1. Pending questions resolved for 2020/07/19 meeting
2. **Release for Member AGM**

### Implementation

It has been decided in  the WG to implement the solution using [discourse](https://www.discourse.org). 

### Features:

- The forum will be open to anyone interested to the Erlang foundations without requiring a member account.  
- Members will get a specific badge  showing their level (contributing, lifetime member, ...)
- Members of a working groups will get also a specific badge and permissions given by the Chair or anyone allwoed by the chair/group for it
- WG will have the possibility to setup private discussion topics/sections

### Pending questions

- [ ] Hosting of the solution. We could either host it via[ the service of the discourse team](https://www.discourse.org/pricing) or host it ourself. (see comment about it)
- [ ] member identification we need a way for the members to tell to the forum they are members of the ErlEF. How will it work?
- [ ] do we need to automate the notification process to warn the group but also interested WGs(those which the member is part) a member has registered 

### Tasks

- [ ] benoît: contact discourse team about pricing ad possiboilities to handle our own features

TBD

**Comment by benoitc** [comment]
> ### Pending questions
> * [ ]  Hosting of the solution. We could either host it via[ the service of the discourse team](https://www.discourse.org/pricing) or host it ourself. (see comment about it)

i think it wouuld be easier to setup our own instance for it with proper backup. We don't really need HA for now. Discourse can easily be installed to some cloud services using templates . The bonus is that it would makes it easier for us to handle the addition of new services/scripts


> * [ ]  member identification we need a way for the members to tell to the forum they are members of the ErlEF. How will it work?

We talk sometimes ago to have a way for the member to get its own member ID using its page on the website (cc @starbelly ). So the solution ( as already been discussed) can be as simple as having the following process:

1. The member retrieve its ID on the erlef accout page 
2. The member register its ID in its discourse profile (after he registered)
3. A separate service check if the ID is valid

Note we may want to have some kind of TOKEN generated for each members when they ask for instead of having an ID. Doing that way would simplify the validiation.


> * [ ]  do we need to automate the notification process to warn the group but also interested WGs(those which the member is part) a member has registered

Main goal of it is to allows the chairs to add the permission to the member to access to their private topics and possibly add a  badge

**Comment by peerst** [comment]
Sorry don't have bandwidth for this currently

**Comment by benoitc** [comment]
> We talk sometimes ago to have a way for the member to get its own member ID using its page on the website (cc @starbelly ). So the solution ( as already been discussed) can be as simple as having the following process:
> 
> 1. The member retrieve its ID on the erlef accout page
> 2. The member register its ID in its discourse profile (after he registered)
> 3. A separate service check if the ID is valid
> 
> Note we may want to have some kind of TOKEN generated for each members when they ask for instead of having an ID. Doing that way would simplify the validiation.

Wouldn't it be easier to rely  on the email used on wild apricot? 

1. The user enter its email used for wild apricot. We check if it's the database and send a mail back to the user with a unique token to reuse. Thoughts?
